apiVersion: apps/v1
kind: Deployment
metadata:
  name: santa1234-deployment
spec:
  selector:
    matchLabels:
      app: santa1234
  replicas: 2
  template:
    metadata:
      labels:
        app: santa1234
    spec:
      containers:
        - name: santa1234
          image: rido4good/santa1234:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080 # The port that the container is running on in the cluster
